"""Prompt strings for LLM tasks."""

from .index_file_system import INDEX_FILE_SYSTEM_PROMPT
from .subsystem_builder_system import (
    SUBSYSTEM_BATCH_SYSTEM_PROMPT,
    SUBSYSTEM_BUILDER_SYSTEM_PROMPT,
    SUBSYSTEM_CLUSTER_SYSTEM_PROMPT,
    SUBSYSTEM_MERGE_SYSTEM_PROMPT,
)
from .wiki_builder_system import WIKI_BUILDER_SYSTEM_PROMPT
from .wiki_sidebar_system import WIKI_SIDEBAR_SYSTEM_PROMPT

__all__ = [
    "INDEX_FILE_SYSTEM_PROMPT",
    "SUBSYSTEM_BATCH_SYSTEM_PROMPT",
    "SUBSYSTEM_BUILDER_SYSTEM_PROMPT",
    "SUBSYSTEM_CLUSTER_SYSTEM_PROMPT",
    "SUBSYSTEM_MERGE_SYSTEM_PROMPT",
    "WIKI_BUILDER_SYSTEM_PROMPT",
    "WIKI_SIDEBAR_SYSTEM_PROMPT",
]
